name: 修改DTB

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "platform"
        required: true
        default: "ds920p"
      pcie_root:
        description: "pcie_root"
        required: true
        default: "00:1f.2"

jobs:
  build:
    runs-on: ubuntu-latest
    name: 修改 "${{ github.event.inputs.platform }} DTB"

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3

      - name: 准备构建环境
        run: |
          sudo apt -qq update && sudo apt upgrade -y
          sudo apt -qq install -y device-tree-compiler
          git clone https://github.com/jumkey/redpill-load redpill-load
          cp -ar redpill-load/redpill-dtb ./
          rm -rf redpill-load

      - name: DTB转DTS
        run: |
          sha256sum redpill-dtb/releases/model_${{ github.event.inputs.platform }}.dtb
          dtc -I dtb -O dts -o output.dts redpill-dtb/releases/model_${{ github.event.inputs.platform }}.dtb

      - name: 修改DTS
        run: |
          echo "------"
          cat output.dts
          echo "------"
          sed -n '/internal_slot@0/,/led_green/p' output.dts
          sed -i '/internal_slot@0/,/led_green/{s/pcie_root.*/pcie_root = \"${{ github.event.inputs.pcie_root }}\";/}' output.dts
          sed -n '/internal_slot@0/,/led_green/p' output.dts
          echo "------"
          sed -n '/internal_slot@1/,/led_green/p' output.dts
          sed -i '/internal_slot@1/,/led_green/{s/pcie_root.*/pcie_root = \"${{ github.event.inputs.pcie_root }}\";/}' output.dts
          sed -n '/internal_slot@1/,/led_green/p' output.dts
          echo "------"
          sed -n '/internal_slot@2/,/led_green/p' output.dts
          sed -i '/internal_slot@2/,/led_green/{s/pcie_root.*/pcie_root = \"${{ github.event.inputs.pcie_root }}\";/}' output.dts
          sed -n '/internal_slot@2/,/led_green/p' output.dts
          echo "------"
          sed -n '/internal_slot@3/,/led_green/p' output.dts
          sed -i '/internal_slot@3/,/led_green/{s/pcie_root.*/pcie_root = \"${{ github.event.inputs.pcie_root }}\";/}' output.dts
          sed -n '/internal_slot@3/,/led_green/p' output.dts
          echo "------"

      - name: DTS转DTB
        run: |
          dtc -I dts -O dtb -o model_${{ github.event.inputs.platform }}.dtb output.dts
          sha256sum model_${{ github.event.inputs.platform }}.dtb

      - name: 覆盖DTB
        run: |
          cp -a model_${{ github.event.inputs.platform }}.dtb redpill-dtb/releases/model_${{ github.event.inputs.platform }}.dtb
          sha256sum redpill-dtb/releases/model_${{ github.event.inputs.platform }}.dtb

      - name: 修改universal.json
        run: |
          echo "------"
          cat redpill-dtb/recipes/universal.json
          echo "------"
          sed -n '/\"model_${{ github.event.inputs.platform }}.dtb\"/,/\"packed\"/p' redpill-dtb/recipes/universal.json
          sed -i "/\"model_${{ github.event.inputs.platform }}.dtb\"/,/\"packed\"/{s/\"sha256\".*/\"sha256\": \"$(sha256sum model_${{ github.event.inputs.platform }}.dtb | awk '{print $1}')\",/}" redpill-dtb/recipes/universal.json
          sed -n '/\"model_${{ github.event.inputs.platform }}.dtb\"/,/\"packed\"/p' redpill-dtb/recipes/universal.json
          echo "------"
          sed -i "s|jumkey/redpill-load|$GITHUB_REPOSITORY|" redpill-dtb/recipes/universal.json

      - name: 修改rpext-index.json
        run: |
          echo "------"
          cat redpill-dtb/recipes/universal.json
          echo "------"
          sed -n '/\"id\"/p' redpill-dtb/rpext-index.json
          sed -i 's/\"id\".*/\"id\": \"${{ github.event.inputs.platform }}.dtb\",/' redpill-dtb/rpext-index.json
          sed -n '/\"id\"/p' redpill-dtb/rpext-index.json
          echo "------"
          sed -i "s|jumkey/redpill-load|$GITHUB_REPOSITORY|" redpill-dtb/rpext-index.json

      - name: 提交
        uses: EndBug/add-and-commit@v9.0.0
        with:
          author_name: PuXiongfei
          author_email: pu.xiongfei@qq.com

      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 1
